config/routes.rb
resources :vacancies
resources :candidates

app/models/candidate.rb
# frozen_string_literal: true

class Candidate < ActiveRecord::Base
  enum status: {
    review: 0,
    interview: 1,
    hired: 2
  }

  has_many :VacancyCandidate, dependent: :destroy
  has_many :vacancies, through: 'VacancyCandidate'

  scope :search, ->(term) { where('first_name LIKE :term OR last_name LIKE :term', term: "%#{term}%") }

  validates :first_name, presence: true
  validates :last_name, presence: true
  validate :ensure_active_vacancies

  private

  def ensure_active_vacancies
    if (vacancies.map(&:id) - Vacancy.active.pluck(:id)).present?
      errors.add :vacancies, 'Should associate only active vacancies'
    end
  end
end

app/models/vacancy.rb
# frozen_string_literal: true

class Vacancy < ActiveRecord::Base
  enum level: {
    junior: 0,
    middle: 1,
    senior: 2
  }
  enum status: {
    open: 0,
    review: 1,
    close: 2
  }

  has_many :VacancyCandidate, dependent: :destroy
  has_many :candidates, through: 'VacancyCandidate'

  scope :search, ->(term) { where('name LIKE ?', "%#{term}%") }
  scope :active, -> { where('status != ? AND date_close > ?', statuses[:close], Date.today) }

  validates :name, presence: true
  validate :validate_date_close

  private

  def validate_date_close
    if date_close && (date_close < Date.today)
      errors.add :date_close, 'Date close should be greater than the current'
    end
  end
end

app/models/vacancy_candidate.rb
# frozen_string_literal: true

class VacancyCandidate < ActiveRecord::Base
  belongs_to :vacancy, required: true
  belongs_to :candidate, required: true
end

app/controllers/candidates_controller.rb
# frozen_string_literal: true

class CandidatesController < ApplicationController
  before_action :set_candidate, only: %i[show update destroy edit]

  def index
    search = params.permit(:term)
    @candidates = search.present? ? Candidate.search(search[:term]) : Candidate.all
  end

  def new
    @candidate = Candidate.new
  end

  def create
    @candidate = Candidate.new(candidate_params)
    if @candidate.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to action: :index
    else
      render action: :new
    end
  end

  def edit; end

  def show; end

  def update
    if @candidate.update_attributes(candidate_params)
      flash[:notice] = l(:notice_successful_update)
      redirect_to action: :index
    else
      render action: :edit
    end
  end

  def destroy
    begin
      Candidate.find(params[:id]).destroy
    rescue StandardError
      flash[:error] = l(:error_unable_delete_vacancy)
    end
    flash[:notice] = l(:notice_successful_delete)
    redirect_to action: :index
  end

  private

  def candidate_params
    params.require(:candidate).permit(:first_name, :last_name, :position, :status, vacancy_ids: [])
  end

  def set_candidate
    @candidate = Candidate.find(params[:id])
  end
end

app/controllers/vacancies_controller.rb
# frozen_string_literal: true

class VacanciesController < ApplicationController
  before_action :set_vacancy, only: %i[show update destroy edit]

  def index
    search = params.permit(:term)
    @vacancies = search.present? ? Vacancy.search(search[:term]) : Vacancy.all
  end

  def new
    @vacancy = Vacancy.new
  end

  def create
    @vacancy = Vacancy.new(vacancy_params)
    if @vacancy.save
      flash[:notice] = l(:notice_successful_create)
      redirect_to action: :index
    else
      render action: :new
    end
  end

  def edit; end

  def show; end

  def update
    if @vacancy.update_attributes(vacancy_params)
      flash[:notice] = l(:notice_successful_update)
      redirect_to action: :index
    else
      render action: :edit
    end
  end

  def destroy
    begin
      Vacancy.find(params[:id]).destroy
    rescue StandardError
      flash[:error] = l(:error_unable_delete_vacancy)
    end
    flash[:notice] = l(:notice_successful_delete)
    redirect_to action: :index
  end

  private

  def vacancy_params
    params.require(:vacancy).permit(:name, :level, :status, :date_close, candidate_ids: [])
  end

  def set_vacancy
    @vacancy = Vacancy.find(params[:id])
  end
end

app/views/candidates/_form.html.erb
<%= form_with(model: candidate, local: true) do |form| %>
  <% if candidate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(candidate.errors.count, "error") %> prohibited this candidate from being saved:</h2>

      <ul>
        <% candidate.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.text_field :position %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, options_for_select(Candidate.statuses.keys.to_a) %>
  </div>

  <div class="field">
    <%= form.label :vacancies %><br />
    <%= form.select :vacancy_ids, options_for_select(Vacancy.active.collect {|x| [x.name, x.id]}, candidate.vacancy_ids), {}, :multiple => true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/candidates/edit.html.erb
<h1>Editing Candidate</h1>

<%= render 'form', candidate: @candidate %>

<%= link_to 'Show', @candidate %> |
<%= link_to 'Back', candidates_path %>

app/views/candidates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Candidates</h1>

<h4>Search by candidates:</h4>
<%= form_tag(candidates_path, method: :get) do %>
  <%= text_field_tag(:term, params[:term])%>
  <%= submit_tag 'Search' %>
<% end %>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Position</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @candidates.each do |candidate| %>
      <tr>
        <td><%= candidate.first_name %></td>
        <td><%= candidate.last_name %></td>
        <td><%= candidate.position %></td>
        <td><%= candidate.status %></td>
        <td><%= link_to 'Show', candidate %></td>
        <td><%= link_to 'Edit', edit_candidate_path(candidate) %></td>
        <td><%= link_to 'Destroy', candidate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Candidate', new_candidate_path %>

app/views/candidates/new.html.erb
<h1>New Candidate</h1>

<%= render 'form', candidate: @candidate %>

<%= link_to 'Back', candidates_path %>

app/views/candidates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @candidate.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @candidate.last_name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @candidate.position %>
</p>

<p>
  <strong>Status:</strong>
  <%= @candidate.status %>
</p>

<p>
  <strong>Vacancies:</strong><br>
  <% @candidate.vacancies.each do |vacancy| %>
    <%= link_to vacancy.name, vacancy %><br>
  <% end %>
</p>

<%= link_to 'Edit', edit_candidate_path(@candidate) %> |
<%= link_to 'Back', candidates_path %>

app/views/vacancies/_form.html.erb
<%= form_with(model: vacancy, local: true) do |form| %>
  <% if vacancy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vacancy.errors.count, "error") %> prohibited this vacancy from being saved:</h2>

      <ul>
        <% vacancy.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.select :level, options_for_select(Vacancy.levels.keys.to_a) %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.select :status, options_for_select(Vacancy.statuses.keys.to_a) %>
  </div>

  <div class="field">
    <%= form.label :date_close %>
    <%= form.date_select :date_close %>
  </div>

  <div class="field">
    <%= form.label :candidates %><br />
    <%= form.select :candidate_ids,
                    options_for_select(Candidate.all.map{|c|["#{c.first_name} #{c.last_name}", c.id]}, vacancy.candidate_ids),
                    {}, {multiple: true} %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vacancies/edit.html.erb
<h1>Editing Vacancy</h1>

<%= render 'form', vacancy: @vacancy %>

<%= link_to 'Show', @vacancy %> |
<%= link_to 'Back', vacancies_path %>

app/views/vacancies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vacancies</h1>

<h4>Search by vacancies:</h4>
<%= form_tag(vacancies_path, method: :get) do %>
  <%= text_field_tag(:term, params[:term])%>
  <%= submit_tag 'Search' %>
<% end %>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>

  <tbody>
    <% @vacancies.each do |vacancy| %>
      <tr>
        <td><%= vacancy.name %></td>
        <td><%= link_to 'Show', vacancy %></td>
        <td><%= link_to 'Edit', edit_vacancy_path(vacancy) %></td>
        <td><%= link_to 'Destroy', vacancy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vacancy', new_vacancy_path %>

app/views/vacancies/new.html.erb
<h1>New Vacancy</h1>

<%= render 'form', vacancy: @vacancy %>

<%= link_to 'Back', vacancies_path %>

app/views/vacancies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @vacancy.name %>
</p>

<p>
  <strong>Level:</strong>
  <%= @vacancy.level %>
</p>

<p>
  <strong>Status:</strong>
  <%= @vacancy.status %>
</p>

<p>
  <strong>Date close:</strong>
  <%= @vacancy.date_close %>
</p>

<p>
  <strong>Date created:</strong>

</p>


<p>
  <strong>Candidates:</strong><br>
  <% @vacancy.candidates.each do |candidate| %>
    <%= link_to "#{candidate.first_name}, #{candidate.last_name}" , candidate %><br>
  <% end %>
</p>


<%= link_to 'Edit', edit_vacancy_path(@vacancy) %> |
<%= link_to 'Back', vacancies_path %>